/**
 * pdfReceipt.js — dependency-free PDF generator for payment receipts.
 *
 * Serverless-safe: no pdfkit, no fontkit, no binary assets. Produces a single
 * A4 page using the PDF base-14 Helvetica fonts with WinAnsi encoding (which
 * covers Portuguese accents). Byte offsets for the xref table are computed
 * against a latin1 buffer so the output is a valid PDF.
 *
 * IMPORTANT: a receipt produced here is a payment receipt only — it is NOT an
 * official Brazilian NF-e / NFS-e fiscal invoice. The disclaimer is embedded.
 */

const PAGE_W = 595.28; // A4 width  (points)
const PAGE_H = 841.89; // A4 height (points)
const MARGIN = 64;

const BRL = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export function formatBrl(value) {
  const n = Number(value);
  return Number.isFinite(n) ? BRL.format(n) : "—";
}

// ─── Low-level helpers ─────────────────────────────────────────────────────────

/** Keep only WinAnsi-representable chars; escape PDF string delimiters. */
function pdfEsc(s) {
  return String(s ?? "")
    .replace(/[^\x00-\xFF]/g, "?") // drop chars outside latin1/WinAnsi
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[\r\n\t]+/g, " ");
}

/** Naive word-wrap by character budget (good enough for receipt body text). */
function wrapText(text, maxChars) {
  const words = String(text ?? "").split(/\s+/).filter(Boolean);
  const lines = [];
  let line = "";
  for (const w of words) {
    if (!line) {
      line = w;
    } else if ((line + " " + w).length <= maxChars) {
      line += " " + w;
    } else {
      lines.push(line);
      line = w;
    }
  }
  if (line) lines.push(line);
  return lines;
}

// ─── Content-stream builder ──────────────────────────────────────────────────

function buildContentStream(receipt) {
  const ops = [];
  let y = PAGE_H - MARGIN;

  const setGray = (g) => ops.push(`${g} g`);
  const text = (s, { x = MARGIN, size = 11, bold = false, gray = 0 } = {}) => {
    setGray(gray);
    ops.push("BT");
    ops.push(`${bold ? "/F2" : "/F1"} ${size} Tf`);
    ops.push(`1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm`);
    ops.push(`(${pdfEsc(s)}) Tj`);
    ops.push("ET");
  };
  const gap = (dy) => { y -= dy; };
  const hr = () => {
    ops.push("0.75 G");
    ops.push("0.6 w");
    ops.push(`${MARGIN} ${y.toFixed(2)} m ${(PAGE_W - MARGIN).toFixed(2)} ${y.toFixed(2)} l S`);
    ops.push("0 G");
  };

  // ── Header ──
  text("EnergyPay", { size: 24, bold: true });
  gap(20);
  text("Clearing & Settlement OS", { size: 10, gray: 0.45 });
  gap(34);

  text(receipt.documentTitle || "PAYMENT RECEIPT · RECIBO DE PAGAMENTO", { size: 13, bold: true });
  gap(16);
  hr();
  gap(26);

  // ── Key / value rows ──
  const row = (label, value) => {
    text(label, { size: 9, gray: 0.45 });
    gap(14);
    text(value ?? "—", { size: 12, bold: true });
    gap(22);
  };

  row("RECEIPT ID", receipt.receiptId);
  row("DATE", receipt.paidAt);
  row("PLAN", receipt.planName);
  row("PAYMENT METHOD", receipt.method);
  row("AMOUNT", receipt.amountLabel);
  row("STATUS", receipt.statusLabel || "PAID");

  if (receipt.txHash) row("TRANSACTION HASH", receipt.txHash);
  if (receipt.ledger != null && receipt.ledger !== "") row("LEDGER", String(receipt.ledger));
  if (receipt.network) row("NETWORK", receipt.network);
  if (receipt.explorerUrl) row("EXPLORER", receipt.explorerUrl);

  gap(8);
  hr();
  gap(24);

  // ── Disclaimer (EN + PT) ──
  const maxChars = 92;
  text("NOTICE", { size: 9, gray: 0.45 });
  gap(16);

  const disclaimerEn =
    "This document is a payment receipt generated by EnergyPay. It is not an official Brazilian NF-e/NFS-e fiscal invoice.";
  for (const ln of wrapText(disclaimerEn, maxChars)) {
    text(ln, { size: 9.5, gray: 0.2 });
    gap(13);
  }
  gap(6);
  const disclaimerPt =
    "Este documento e um recibo de pagamento gerado pela EnergyPay. Ele nao substitui uma Nota Fiscal eletronica oficial.";
  for (const ln of wrapText(disclaimerPt, maxChars)) {
    text(ln, { size: 9.5, gray: 0.2 });
    gap(13);
  }

  // ── Footer ──
  y = MARGIN + 8;
  text(`Generated at ${new Date().toISOString()}`, { size: 8, gray: 0.5 });

  return ops.join("\n");
}

// ─── PDF assembler ─────────────────────────────────────────────────────────────

export function renderReceiptPdf(receipt) {
  const content = buildContentStream(receipt);
  const contentLen = Buffer.byteLength(content, "latin1");

  const objects = {
    1: "<< /Type /Catalog /Pages 2 0 R >>",
    2: "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    3:
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] ` +
      `/Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>`,
    4: `<< /Length ${contentLen} >>\nstream\n${content}\nendstream`,
    5: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
    6: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
  };

  let pdf = "%PDF-1.4\n";
  const offsets = {};
  for (let i = 1; i <= 6; i++) {
    offsets[i] = Buffer.byteLength(pdf, "latin1");
    pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, "latin1");
  pdf += "xref\n0 7\n";
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= 6; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "latin1");
}
