/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as X402RouteImport } from './routes/x402'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as SettlementRouteImport } from './routes/settlement'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as P2pRouteImport } from './routes/p2p'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GridRouteImport } from './routes/grid'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClearingRouteImport } from './routes/clearing'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as UtilityUcRouteImport } from './routes/utility.uc'
import { Route as UtilityTusdRouteImport } from './routes/utility.tusd'
import { Route as UtilityConnectionsRouteImport } from './routes/utility.connections'
import { Route as UtilityCertificatesRouteImport } from './routes/utility.certificates'
import { Route as UtilityAreaRouteImport } from './routes/utility.area'
import { Route as ContractsNewRouteImport } from './routes/contracts.new'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiSettlementsTelemetryRouteImport } from './routes/api.settlements.telemetry'
import { Route as ApiP2pValidateRouteImport } from './routes/api.p2p.validate'
import { Route as ApiWalletPublicKeyBalancesRouteImport } from './routes/api.wallet.$publicKey.balances'
import { Route as ApiWalletPublicKeyActivityRouteImport } from './routes/api.wallet.$publicKey.activity'

const X402Route = X402RouteImport.update({
  id: '/x402',
  path: '/x402',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementRoute = SettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const P2pRoute = P2pRouteImport.update({
  id: '/p2p',
  path: '/p2p',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearingRoute = ClearingRouteImport.update({
  id: '/clearing',
  path: '/clearing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityUcRoute = UtilityUcRouteImport.update({
  id: '/utility/uc',
  path: '/utility/uc',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityTusdRoute = UtilityTusdRouteImport.update({
  id: '/utility/tusd',
  path: '/utility/tusd',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityConnectionsRoute = UtilityConnectionsRouteImport.update({
  id: '/utility/connections',
  path: '/utility/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityCertificatesRoute = UtilityCertificatesRouteImport.update({
  id: '/utility/certificates',
  path: '/utility/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityAreaRoute = UtilityAreaRouteImport.update({
  id: '/utility/area',
  path: '/utility/area',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettlementsTelemetryRoute = ApiSettlementsTelemetryRouteImport.update({
  id: '/api/settlements/telemetry',
  path: '/api/settlements/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiP2pValidateRoute = ApiP2pValidateRouteImport.update({
  id: '/api/p2p/validate',
  path: '/api/p2p/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletPublicKeyBalancesRoute =
  ApiWalletPublicKeyBalancesRouteImport.update({
    id: '/api/wallet/$publicKey/balances',
    path: '/api/wallet/$publicKey/balances',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWalletPublicKeyActivityRoute =
  ApiWalletPublicKeyActivityRouteImport.update({
    id: '/api/wallet/$publicKey/activity',
    path: '/api/wallet/$publicKey/activity',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clearing': typeof ClearingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/oracle': typeof OracleRoute
  '/p2p': typeof P2pRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settlement': typeof SettlementRoute
  '/topology': typeof TopologyRoute
  '/treasury': typeof TreasuryRoute
  '/wallet': typeof WalletRoute
  '/x402': typeof X402Route
  '/api/health': typeof ApiHealthRoute
  '/contracts/new': typeof ContractsNewRoute
  '/utility/area': typeof UtilityAreaRoute
  '/utility/certificates': typeof UtilityCertificatesRoute
  '/utility/connections': typeof UtilityConnectionsRoute
  '/utility/tusd': typeof UtilityTusdRoute
  '/utility/uc': typeof UtilityUcRoute
  '/contracts/': typeof ContractsIndexRoute
  '/api/p2p/validate': typeof ApiP2pValidateRoute
  '/api/settlements/telemetry': typeof ApiSettlementsTelemetryRoute
  '/api/wallet/$publicKey/activity': typeof ApiWalletPublicKeyActivityRoute
  '/api/wallet/$publicKey/balances': typeof ApiWalletPublicKeyBalancesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clearing': typeof ClearingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/oracle': typeof OracleRoute
  '/p2p': typeof P2pRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settlement': typeof SettlementRoute
  '/topology': typeof TopologyRoute
  '/treasury': typeof TreasuryRoute
  '/wallet': typeof WalletRoute
  '/x402': typeof X402Route
  '/api/health': typeof ApiHealthRoute
  '/contracts/new': typeof ContractsNewRoute
  '/utility/area': typeof UtilityAreaRoute
  '/utility/certificates': typeof UtilityCertificatesRoute
  '/utility/connections': typeof UtilityConnectionsRoute
  '/utility/tusd': typeof UtilityTusdRoute
  '/utility/uc': typeof UtilityUcRoute
  '/contracts': typeof ContractsIndexRoute
  '/api/p2p/validate': typeof ApiP2pValidateRoute
  '/api/settlements/telemetry': typeof ApiSettlementsTelemetryRoute
  '/api/wallet/$publicKey/activity': typeof ApiWalletPublicKeyActivityRoute
  '/api/wallet/$publicKey/balances': typeof ApiWalletPublicKeyBalancesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clearing': typeof ClearingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/oracle': typeof OracleRoute
  '/p2p': typeof P2pRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settlement': typeof SettlementRoute
  '/topology': typeof TopologyRoute
  '/treasury': typeof TreasuryRoute
  '/wallet': typeof WalletRoute
  '/x402': typeof X402Route
  '/api/health': typeof ApiHealthRoute
  '/contracts/new': typeof ContractsNewRoute
  '/utility/area': typeof UtilityAreaRoute
  '/utility/certificates': typeof UtilityCertificatesRoute
  '/utility/connections': typeof UtilityConnectionsRoute
  '/utility/tusd': typeof UtilityTusdRoute
  '/utility/uc': typeof UtilityUcRoute
  '/contracts/': typeof ContractsIndexRoute
  '/api/p2p/validate': typeof ApiP2pValidateRoute
  '/api/settlements/telemetry': typeof ApiSettlementsTelemetryRoute
  '/api/wallet/$publicKey/activity': typeof ApiWalletPublicKeyActivityRoute
  '/api/wallet/$publicKey/balances': typeof ApiWalletPublicKeyBalancesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/clearing'
    | '/forgot-password'
    | '/grid'
    | '/login'
    | '/notifications'
    | '/oracle'
    | '/p2p'
    | '/register'
    | '/reset-password'
    | '/settlement'
    | '/topology'
    | '/treasury'
    | '/wallet'
    | '/x402'
    | '/api/health'
    | '/contracts/new'
    | '/utility/area'
    | '/utility/certificates'
    | '/utility/connections'
    | '/utility/tusd'
    | '/utility/uc'
    | '/contracts/'
    | '/api/p2p/validate'
    | '/api/settlements/telemetry'
    | '/api/wallet/$publicKey/activity'
    | '/api/wallet/$publicKey/balances'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/clearing'
    | '/forgot-password'
    | '/grid'
    | '/login'
    | '/notifications'
    | '/oracle'
    | '/p2p'
    | '/register'
    | '/reset-password'
    | '/settlement'
    | '/topology'
    | '/treasury'
    | '/wallet'
    | '/x402'
    | '/api/health'
    | '/contracts/new'
    | '/utility/area'
    | '/utility/certificates'
    | '/utility/connections'
    | '/utility/tusd'
    | '/utility/uc'
    | '/contracts'
    | '/api/p2p/validate'
    | '/api/settlements/telemetry'
    | '/api/wallet/$publicKey/activity'
    | '/api/wallet/$publicKey/balances'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/clearing'
    | '/forgot-password'
    | '/grid'
    | '/login'
    | '/notifications'
    | '/oracle'
    | '/p2p'
    | '/register'
    | '/reset-password'
    | '/settlement'
    | '/topology'
    | '/treasury'
    | '/wallet'
    | '/x402'
    | '/api/health'
    | '/contracts/new'
    | '/utility/area'
    | '/utility/certificates'
    | '/utility/connections'
    | '/utility/tusd'
    | '/utility/uc'
    | '/contracts/'
    | '/api/p2p/validate'
    | '/api/settlements/telemetry'
    | '/api/wallet/$publicKey/activity'
    | '/api/wallet/$publicKey/balances'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ClearingRoute: typeof ClearingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GridRoute: typeof GridRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OracleRoute: typeof OracleRoute
  P2pRoute: typeof P2pRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettlementRoute: typeof SettlementRoute
  TopologyRoute: typeof TopologyRoute
  TreasuryRoute: typeof TreasuryRoute
  WalletRoute: typeof WalletRoute
  X402Route: typeof X402Route
  ApiHealthRoute: typeof ApiHealthRoute
  ContractsNewRoute: typeof ContractsNewRoute
  UtilityAreaRoute: typeof UtilityAreaRoute
  UtilityCertificatesRoute: typeof UtilityCertificatesRoute
  UtilityConnectionsRoute: typeof UtilityConnectionsRoute
  UtilityTusdRoute: typeof UtilityTusdRoute
  UtilityUcRoute: typeof UtilityUcRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  ApiP2pValidateRoute: typeof ApiP2pValidateRoute
  ApiSettlementsTelemetryRoute: typeof ApiSettlementsTelemetryRoute
  ApiWalletPublicKeyActivityRoute: typeof ApiWalletPublicKeyActivityRoute
  ApiWalletPublicKeyBalancesRoute: typeof ApiWalletPublicKeyBalancesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x402': {
      id: '/x402'
      path: '/x402'
      fullPath: '/x402'
      preLoaderRoute: typeof X402RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlement': {
      id: '/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof SettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2p': {
      id: '/p2p'
      path: '/p2p'
      fullPath: '/p2p'
      preLoaderRoute: typeof P2pRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clearing': {
      id: '/clearing'
      path: '/clearing'
      fullPath: '/clearing'
      preLoaderRoute: typeof ClearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility/uc': {
      id: '/utility/uc'
      path: '/utility/uc'
      fullPath: '/utility/uc'
      preLoaderRoute: typeof UtilityUcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility/tusd': {
      id: '/utility/tusd'
      path: '/utility/tusd'
      fullPath: '/utility/tusd'
      preLoaderRoute: typeof UtilityTusdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility/connections': {
      id: '/utility/connections'
      path: '/utility/connections'
      fullPath: '/utility/connections'
      preLoaderRoute: typeof UtilityConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility/certificates': {
      id: '/utility/certificates'
      path: '/utility/certificates'
      fullPath: '/utility/certificates'
      preLoaderRoute: typeof UtilityCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility/area': {
      id: '/utility/area'
      path: '/utility/area'
      fullPath: '/utility/area'
      preLoaderRoute: typeof UtilityAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/new': {
      id: '/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ContractsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settlements/telemetry': {
      id: '/api/settlements/telemetry'
      path: '/api/settlements/telemetry'
      fullPath: '/api/settlements/telemetry'
      preLoaderRoute: typeof ApiSettlementsTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p2p/validate': {
      id: '/api/p2p/validate'
      path: '/api/p2p/validate'
      fullPath: '/api/p2p/validate'
      preLoaderRoute: typeof ApiP2pValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/$publicKey/balances': {
      id: '/api/wallet/$publicKey/balances'
      path: '/api/wallet/$publicKey/balances'
      fullPath: '/api/wallet/$publicKey/balances'
      preLoaderRoute: typeof ApiWalletPublicKeyBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/$publicKey/activity': {
      id: '/api/wallet/$publicKey/activity'
      path: '/api/wallet/$publicKey/activity'
      fullPath: '/api/wallet/$publicKey/activity'
      preLoaderRoute: typeof ApiWalletPublicKeyActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ClearingRoute: ClearingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GridRoute: GridRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OracleRoute: OracleRoute,
  P2pRoute: P2pRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettlementRoute: SettlementRoute,
  TopologyRoute: TopologyRoute,
  TreasuryRoute: TreasuryRoute,
  WalletRoute: WalletRoute,
  X402Route: X402Route,
  ApiHealthRoute: ApiHealthRoute,
  ContractsNewRoute: ContractsNewRoute,
  UtilityAreaRoute: UtilityAreaRoute,
  UtilityCertificatesRoute: UtilityCertificatesRoute,
  UtilityConnectionsRoute: UtilityConnectionsRoute,
  UtilityTusdRoute: UtilityTusdRoute,
  UtilityUcRoute: UtilityUcRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  ApiP2pValidateRoute: ApiP2pValidateRoute,
  ApiSettlementsTelemetryRoute: ApiSettlementsTelemetryRoute,
  ApiWalletPublicKeyActivityRoute: ApiWalletPublicKeyActivityRoute,
  ApiWalletPublicKeyBalancesRoute: ApiWalletPublicKeyBalancesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
